name: Dynamic Docker Labels - DockerHub

on:
  push:
    branches:
      - feature/task1-docker-labels-gh-actions

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: 'Set Dockerfile environment variable'
      run: echo "DOCKERFILE_URL=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/blob/${GITHUB_REF##*/}/samples/dynamic-labels/Dockerfile" >> $GITHUB_ENV
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./samples/dynamic-labels/Dockerfile
        push: true
        tags: toddysm/tmstests:latest
        build-args: |
          IMAGE_COMMITTER=${{ github.actor }}
          IMAGE_DOCKERFILE=${DOCKERFILE_URL}
          IMAGE_COMMIT_SHA=${{ github.sha }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
