name: Dynamic Docker Labels - DockerHub

on:
  push:
    branches:
      - feature/task1-docker-labels-gh-actions

env:
  DOCKERFILE_LOCATION=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/tree/$GITHUB_BASE_REF/samples/dynamic-labels/Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./samples/dynamic-labels/Dockerfile
        push: true
        tags: toddysm/tmstests:latest
        build-args: "IMAGE_COMMITTER=$GITHUB_ACTOR,IMAGE_DOCKERFILE=${{ env.DOCKERFILE_LOCATION }},IMAGE_COMMIT_SHA=$GITHUB_SHA"

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
