name: Dynamic Docker Labels - DockerHub

on:
  push:
    branches:
      - feature/task1-docker-labels-gh-actions

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: 'Print environment variables'
      run: echo 'User:$GITHUB_ACTOR Branch:$GITHUB_REF Commit SHA:$GITHUB_SHA'
